server:
  port: 8089

spring:
  application:
    name: JobSearch

  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:h2:./db/job_search;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver



  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

logging:
  file: 
    path: logs
  level:
    root: info
    kg.attractor.job_search: debug

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"


